### PR TITLE
Use cmake module FindPython and update cmake build documentation

### PR DESCRIPTION
**Pull request by charlesfleche**
@sirpalee I'm trying the CMake  and suggestion improvements as it goes. It is still [WIP], but that way I show you what I am changing, just in case you are working on the same things at the same time.

- ~~Make the `docs` target optional and conditional on the presence of Doxygen. This fixes an install issue where installation would fail if the build was not run with `build_all`~~
- ~~Remove `build_all` target, in favor of default build target~~
- Use the cmake module FindPython to ease building against non-system python builds
- Update cmake build documentation

### CODE REVIEW

**Comment by charlesfleche** [comment]
It builds, but I cannot run your dev @sirpalee: it fails with
`00:00:00   527MB ERROR   | [gpu] Unable to load Optix library, NVIDIA driver 390.48 is either too old or missing the Optix library (CPU-rendering with Optix GPU-denoiser)`

Current upstream `master` branch f1d3f7e7e7ee802bc440bee20ec9c0f2162248d9 does build (abuild) and run correctly.

**Comment by sirpalee** [comment]
@charlesfleche yeah, that's probably due to the work I started on using the OptiX denoiser for the beauty. I'll check on using some Arnold API to determine if a supported GPU/driver is available, but I'll have to ask for your help to test it, as I can't go back on driver versions.

If the documentation is enabled (there is a flag in options.cmake to turn it off), I prefer throwing and error rather than a message and returning from the function. That's better than showing a message that people easily miss, and then they can't figure out why the documentation is not being generated.

I'll get back to you on build_all and adding doxygen to ALL, but I had some inconveniences in my current development workflow when doxygen is part of ALL (I'm using CLion); it always ran even if I built a single target. I'll do some research on what's the canonical way of running doxygen.

Thanks for the suggestions and feedback!

**Comment by sirpalee** [comment]
I added a new take on generating doxygen documentation. My main concern was that custom targets are always out of date. (see `The target has no output file and is always considered out of date even if the commands try to create a file with the name of the target.`) This means if we add the doxygen command to ALL, doxygen always runs unless the user explicitly sets BUILD_DOCS to OFF.

I found a workaround. I'm adding a custom command (where dependencies are taken into account), and adding a custom target that depends on the output of my custom command. (the `index.html` in this case) My custom command depends on the markdown files and I glob the header files from the project. This way doxygen is only regenerated when there is a change to doxyfile, any of the markdown files or any of the header files.

While `globbing files` is generally frowned up in cmake, luckily we have a new flag (another reason to bump up to 3.12), CONFIGURE_DEPENDS, which will trigger a rebuild when the list of files changes.

I think this approach solves my issue of always rebuilding the documentation and your issue of the documentation not being part of the `all` target. What do you think?

**Comment by charlesfleche** [comment]
I've never tried it, but maybe we could use doxygen_add_docs ? I'd expect this function to prevent unecessary doc rebuilds.
https://cmake.org/cmake/help/v3.9/module/FindDoxygen.html#command:doxygen_add_docs
Available in CMake >= 3.9, though.

**Comment by charlesfleche** [comment]
> @charlesfleche yeah, that's probably due to the work I started on using the OptiX denoiser for the beauty. I'll check on using some Arnold API to determine if a supported GPU/driver is available, but I'll have to ask for your help to test it, as I can't go back on driver versions.

Sure, whatever you need.

**Comment by sirpalee** [comment]
@charlesfleche I checked the [source](https://github.com/Kitware/CMake/blob/3a77329c40803b02fe33ffc86197c1baf291aaff/Modules/FindDoxygen.cmake#L1104) of doxygen_add_docs and it's just using an add_custom_target. That'll have the same issue of always being out of date.

For now, I'm going to go with the current solution, and use a mix of an add_custom_command and add_custom_target. I'll see if there are ways to simplify the code though.

**Comment by sirpalee** [comment]
@charlesfleche I changed how the optix denoiser filters are created and they are now optional. Can you please check 0baa374b073c09b7ac472dc5a514ae1905d2e732 ?

**Comment by charlesfleche** [comment]
> Can you please check 0baa374 ?

It works !

**Comment by charlesfleche** [comment]
What should we do with this PR ? What about reverting the Doxygen related patches, keeping the ones that remove `build_all`, and upgrade `find_package(PythonLibs)` to the more modern [`FindPython`](https://cmake.org/cmake/help/git-stage/module/FindPython.html) ?

Or trash this PR entirely ?

**Comment by charlesfleche** [comment]
I'm having an hard building with CMake for Houdini, I can't find the right CMake variables to set to find boost. Would you mind to share the CMake command you run to build with this configuration ? Thanks.

**Comment by sirpalee** [comment]
I'm fine with going to the new FindPython, I doubt are losing any functionality. I would keep the build_all target, simply for the sake of my workflow, since it doesn't affect anything.

Here is my config of building for Houdini 18.0.247

```
-DARNOLD_LOCATION=/home/sirpalee/apps/arnold-6.0.1.0
-DUSD_LIB_PREFIX=libpxr_
-DUSD_INCLUDE_DIR=/opt/hfs18.0/toolkit/include
-DUSD_LIBRARY_DIR=/opt/hfs18.0/dsolib
-DBUILD_USE_CUSTOM_BOOST=ON
-DBoost_INCLUDE_DIRS=/opt/hfs18.0/toolkit/include/hboost
-DBoost_LIBRARIES=/opt/hfs18.0/dsolib/libhboost_python.so
-DTBB_FOUND=ON
-DTBB_INCLUDE_DIRS=/opt/hfs18.0/toolkit/include
-DTBB_LIBRARIES=/opt/hfs18.0/dsolib/libtbb.so
-DCMAKE_INSTALL_MESSAGE=LAZY
-DCMAKE_INSTALL_PREFIX=/home/sirpalee/dist/arnold-usd-houdini
```

**Comment by charlesfleche** [comment]
I've removed the doxygen and build_all related patches. I'd however suggest that the `build_all` may be confusing as the usual ALL target is supposed to be the well known equivalent.

The new patches replace find_package PythonLibs by Python2, which better allow to build against a custom python. And I've updated the document with some cmake examples.

**Comment by sirpalee** [comment]
@charlesfleche I'm going to merge in your pull request, thanks for your work! I'll see if I can figure out a better workflow for myself and get rid of the build_all target, you are right it can be confusing.

**Pull request merged**
